name: Tests & Allure Report

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: staging

    env:
      ENV: staging
      BASE_API_URL: ${{ vars.BASE_API_URL }}
      BASE_UI_URL: ${{ vars.BASE_UI_URL }}
      BROWSER: chromium
      AUTH_KEY: ${{ secrets.AUTH_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

#      - name: Install Playwright browsers
#        run: playwright install --with-deps chromium

      - name: Cache Allure CLI
        uses: actions/cache@v4
        with:
          path: ~/.npm-global
          key: allure-cli-${{ runner.os }}

      - name: Install Allure 3
        run: |
          npm config set prefix ~/.npm-global
          npm install -g allure
          echo "$HOME/.npm-global/bin" >> $GITHUB_PATH

      - name: Run API gate
        run: pytest -m api
        continue-on-error: true

      - name: Publish Pytest Report
        uses: dorny/test-reporter@v3
        if: always() # Runs even if your pytest suite has failing tests
        with:
          name: Pytest Results
          path: reports/pytest-report.xml
          reporter: java-junit

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        if: always() # Ensures the HTML report is saved even if tests fail
        with:
          name: pytest-html-report
          path: reports/report.html

      - name: Get Allure history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          sparse-checkout: history.jsonl
          sparse-checkout-cone-mode: false

      - name: Restore history file
        run: |
          mkdir -p allure-report
          if [ -f gh-pages/history.jsonl ]; then
            cp gh-pages/history.jsonl allure-report/history.jsonl
          fi
        continue-on-error: true

      - name: Generate Allure Report
        run: allure generate allure-results --output allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true